services:
  jellybrry:
    image: ghcr.io/eightbitmagnets/jellybrry:latest
    container_name: jellybrry
    restart: unless-stopped
    ports:
      - "6070:6070"
    volumes:
      - ./config:/config
    environment:
      - THEME=jellybrry